# Generated by Django 3.2.3 on 2021-05-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210524_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addres',
            new_name='address',
        ),
    ]
