# Generated by Django 3.2.3 on 2021-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210525_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
